# Generated by Django 4.2.19 on 2025-02-09 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_token',
            field=models.TextField(blank=True, help_text='OAuth token for LinkedIn'),
        ),
        migrations.CreateModel(
            name='ScrapingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(help_text='URL of the blog/website to scrape')),
                ('topic', models.CharField(help_text='Topic or category to focus on', max_length=200)),
                ('interval', models.CharField(choices=[('6H', 'Every 6 Hours'), ('12H', 'Every 12 Hours'), ('24H', 'Daily'), ('48H', 'Every 2 Days'), ('72H', 'Every 3 Days'), ('168H', 'Weekly')], default='24H', max_length=4)),
                ('post_style', models.CharField(choices=[('NEWS', 'News Style'), ('INSIGHTS', 'Industry Insights'), ('SUMMARY', 'Brief Summary'), ('QUOTES', 'Key Quotes')], default='NEWS', max_length=10)),
                ('hashtags', models.CharField(blank=True, help_text='Comma-separated hashtags for LinkedIn posts', max_length=500)),
                ('custom_template', models.TextField(blank=True, help_text='Custom post template. Use {title}, {summary}, {url} as placeholders')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('summary', models.TextField()),
                ('linkedin_post_text', models.TextField()),
                ('posted_to_linkedin', models.BooleanField(default=False)),
                ('linkedin_post_id', models.CharField(blank=True, max_length=100)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.scrapingschedule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
