# Generated by Django 4.2.19 on 2025-02-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_userprofile_linkedin_token_scrapingschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_user_id',
            field=models.CharField(blank=True, help_text='LinkedIn User ID for posting', max_length=100),
        ),
    ]
