version: "3.9"
services:
  web:
    build: .
    command: gunicorn personal.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A personal worker -l info
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - redis
      - web

  celery-beat:
    build: .
    command: celery -A personal beat -l info
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - redis
      - web

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"