# Generated by Django 5.1.4 on 2025-01-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_delete_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liked',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='post_id',
        ),
    ]
