# Generated by Django 5.1.4 on 2025-01-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_liked_post_likes_rename_id_post_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
    ]
