# Generated by Django 4.2.19 on 2025-02-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_a', models.CharField(max_length=255)),
                ('drug_b', models.CharField(max_length=255)),
                ('drug_a_normalized', models.CharField(max_length=255)),
                ('drug_b_normalized', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.IntegerField(choices=[(1, 'Low Risk'), (2, 'Moderate Risk'), (3, 'High Risk')])),
                ('source', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['drug_a_normalized', 'drug_b_normalized'], name='api_drugint_drug_a__b38361_idx'), models.Index(fields=['active'], name='api_drugint_active_7d5380_idx')],
                'unique_together': {('drug_a_normalized', 'drug_b_normalized')},
            },
        ),
    ]
